settings:
  legacy:
    force: true
    interval: 100ms
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: 402
  path: .
  commands:
    run: 
      status: true
  args:
  - -v=4
  - --mongo_url=127.0.0.1:27018
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
    - json
    ignored_paths:
    - .git
    - vendor
- name: 402-test
  path: .
  commands:
    test:
      output: true
      status: true
      args:
      - -coverprofile=coverage.out
    vet:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
    - json
    ignored_paths:
    - .git
    - vendor
    scripts:
      - type: before
        command: docker run -d --name mongo -p 27018:27017 mongo:3.6.3
        global: true
        output: true
      - type: before
        command: go test ./... -cover -count=1
        output: true
      - type: after
        command: docker rm -f mongo
        global: true
        output: true